### ISSUE TITLE
Error: Unable to access jarfile /minecraft/paperclip.jar

### ISSUE THREAD

**Issue by vecnar** [TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate#17] opened 2023-03-05 20:40 UTC
Hi James,

I hope it is something that I overlooked or some connection problem.

I had to reinstall my raspberry pi due to some boot fault and now unable to create your docker. I thought it is my old config that was causing the problems with custom ports so I started clean in order to troubleshoot and below are my findings.

REPOSITORY                                         TAG       IMAGE ID       CREATED        SIZE
05jchambers/legendary-minecraft-geyser-floodgate   latest    3acd32d5c474   5 weeks ago    402MB

Dns settings on raspberry pi are 1.1.1.1 and 9.9.9.9 to exclude adguard.

First run
`
pi@pi4:~ $ docker run -it -v /docker/minecraft/.minecraft-data:/minecraft -p 25565:25565 -p 19132:19132/udp -p 19132:19132 -e TZ="Europe/Dublin" 05jchambers/legendary-minecraft-geyser-floodgate:latest
Paper Minecraft Java Server Docker + Geyser/Floodgate script by James A. Chambers
Latest version always at https://github.com/TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate
Don't forget to set up port forwarding on your router!  The default port is 25565 and the Bedrock port is 19132
Port used: 25565
Bedrock port used: 19132
Taking ownership of all server files/folders in /minecraft...
Complete
Updating to most recent paperclip version ...
Unable to connect to update website (internet connection may be down).  Skipping update ...
Starting Minecraft server...

**Error: Unable to access jarfile /minecraft/paperclip.jar**
`

Downloaded latest file from https://papermc.io/downloads and placed in /docker/minecraft/.minecraft-data/paperclip.jar and now getting below. I tried #442 and #440.

I am not seeing any world files created or able to connect to server from minecraft bedrock client.

Second run

`
pi@pi4:~ $ docker run -it -v /docker/minecraft/.minecraft-data:/minecraft -p 25565:25565 -p 19132:19132/udp -p 19132:19132 -e TZ="Europe/Dublin" -e NoScreen=Y 05jchambers/legendary-minecraft-geyser-floodgate:latest
Paper Minecraft Java Server Docker + Geyser/Floodgate script by James A. Chambers
Latest version always at https://github.com/TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate
Don't forget to set up port forwarding on your router!  The default port is 25565 and the Bedrock port is 19132
Port used: 25565
Bedrock port used: 19132
Taking ownership of all server files/folders in /minecraft...
Complete
Updating to most recent paperclip version ...
Unable to connect to update website (internet connection may be down).  Skipping update ...

Starting Minecraft server...
`

Let me know if you would like me to test anything.

Thank you in advance,

Oleg

**Comment by TheRemote** [comment] 2023-03-05 20:45
Hey Oleg,

DNS does not appear to be working in Docker here:

```
Updating to most recent paperclip version ...
Unable to connect to update website (internet connection may be down). Skipping update ...
```

We just had a really similar instance here (for Bedrock): https://github.com/TheRemote/Legendary-Bedrock-Container/issues/12.  The issue is the same though.

Can you try doing a:

`docker run --rm -it alpine ping papermc.io`

What you should find is that your Docker DNS configuration is just not working.  You won't even be able to ping.  This is due to the DNS / PiHole configuration and it was for the person linked as well.

Hopefully that helps, I'm sure it will work once you can resolve DNS names within the container again!

**Comment by vecnar** [comment] 2023-03-05 22:28
Thank you for a quick reply!

This is a clean Debian buster install and no pihole or adguard installed on it, but the same problem as per the post you referred to.

pi@pi4:~ $ uname -a
Linux pi4 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux
pi@pi4:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"


I ran the ping from docker and it failed to resolve dns name.

`pi@pi4:~ $ docker run --rm -it alpine ping papermc.io
ping: bad address papermc.io`

Passing dns server to alpine docker container worked

`pi@pi4:~ $ docker run --rm -it --dns 1.1.1.1 alpine ping papermc.io
PING papermc.io (172.67.72.198): 56 data bytes
ping: clock_gettime(MONOTONIC) failed
`

Passing dns parameter to your docker container unfortunately didn't' help

`docker run -it --dns 1.1.1.1 -v /docker/minecraft/.minecraft-data:/minecraft -p 25565:25565 -p 19132:19132/udp -p 19132:19132 -e TZ="Europe/Dublin" 05jchambers/legendary-minecraft-geyser-floodgate:latest`

Thank you for pointing towards the problem, I will try to do some searching online and hopefully will get it resolved.

**Comment by TheRemote** [comment] 2023-03-05 23:34
As far as I'm aware you can't use it on Debian Buster.  That's too old of a version basically.

The current version of Raspberry Pi OS is Bullseye.  It will "just work" in Bullseye.  If you figure out how to get it working in Buster let me know but it hasn't worked on that version for at least a year or more I'd say.

Is your Docker installed from the Raspberry Pi repositories?  It's probably a very old version then.  The latest OpenJDK in Debian Buster is OpenJDK 11 and the current version is OpenJDK 18 so it's very far behind.

Can you share your:

`docker --version`

On my system:

```
james@pop-os:~/Arduino/libraries/ESP32_C3_ISR_Servo/src$ docker --version
Docker version 20.10.12, build 20.10.12-0ubuntu4
```

If you go to the Raspberry Pi repositories at http://archive.raspbian.org/raspbian/pool/main/d/docker.io/ I see the versions they are serving up as 18.03, 18.06, 19.03 and 20.10.

Since you are on Raspberry Pi Buster and not Bullseye we can assume that it's not going to be 20.10 most likely.  If it's one of the 18.x ones that is particularly old.

If this is a clean install I would recommend installing the current Bullseye version.  There's nothing to lose and it will immediately fix it without any further configuration!

**Comment by vecnar** [comment] 2023-03-06 00:12
I am not sure why I chose buster, probably just had it handy.
I will reinstall using bullseye as per your suggestion as something will stop working and everything will have to be reinstalled again, thank you for pointing that out!

I installed my docker using below commands from my notes about previous install. Looks like It pulls latest version during install so I probably had some version that was working during past install.
`curl -sSL https://get.docker.com | sh`
`sudo usermod -aG docker ${USER}`
`sudo apt-get install libffi-dev libssl-dev`
`sudo apt install python3-dev`
`sudo apt-get install -y python3 python3-pip`
`sudo pip3 install docker-compose`
`sudo systemctl enable docker`

`pi@pi4:~ $ docker --version`
`Docker version 23.0.1, build a5ee5b1`


I noticed that dns query gets resolved only on second or third time and passing dns parameter doesn't make any difference. Subsequent launches are a mix of successes and failures.
`docker run --rm -it alpine ping papermc.io`

Thank you for your help!

**Comment by vecnar** [comment] 2023-03-06 17:54
Hi James,
I am not sure if I should close it or you need to do it but thought to add my bullseye docker version, os and how it was installed.

pi@pi4b:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

`pi@pi4b:~ $ docker --version`
`Docker version 23.0.1, build a5ee5b1`

`uname -a`
`Linux pi4b 5.15.84-v7l+ #1613 SMP Thu Jan 5 12:01:26 GMT 2023 armv7l GNU/Linux`

To install I used below, probably not correct or safe but it worked.
`curl -sSL https://get.docker.com | sh`
`sudo usermod -aG docker ${USER}`
`sudo systemctl enable docker`

I also had to add below to existing line in /boot/cmdline.txt and reboot in order for memory limit to work.
`cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1`

I used `docker-compose.yaml` configuration file 
[docker-compose.yaml.txt](https://github.com/TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate/files/10901055/docker-compose.yaml.txt)
and `docker compose up -d` command to create and start the docker.

On first start-ups of the old world it was very slow, destroying the block of stone would take around 5 seconds to disappear and I couldn't do anything else but leaving it overnight running and today it is back to normal game play.

Thanks again for a good docker and sorry for making unnecessary noise here not relating to your docker.

**Comment by TheRemote** [comment] 2023-03-06 18:04
No problem at all, thanks for your very detailed report of how it went!  This should help others as well.

I'll take care of closing it, I'm so glad you got it up and running though, enjoy and take care!

**Closed as completed by TheRemote** 2023-03-06 18:04 UTC
