### ISSUE TITLE
Unable to connect with bedrock client, Java version that Geyser requires (1.19.4)

### ISSUE THREAD

**Issue by vecnar** [TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate#18] opened 2023-03-15 19:13 UTC
Hi James,

docker image used: 05jchambers/legendary-minecraft-geyser-floodgate  image id:3acd32d5c474 created:6weeks ago

Hope you are doing well after recent cold spells.

I was able to play yesterday from windows 10 with bedrock client but today I got below error first
`[17:55:29 INFO]: [Geyser-Spigot] Bedrock user with ip: /192.168.2.135 has disconnected for reason Outdated Geyser proxy! This server supports the following Bedrock versions: 1.19.20, 1.19.21/1.19.22, 1.19.30/1.19.31, 1.19.40/1.19.41, 1.19.50/1.19.51, 1.19.60, 1.19.62
?aThe latest Geyser release supports this Bedrock version. A server admin can download the update at ?9https://ci.geysermc.org
` 
 so I restarted docker a few times in hopes it will update necessary components and now I am getting below error regarding java version. 
`Your server software does not support the Java version that Geyser requires (1.19.4). Please install ViaVersion (https://ci.viaversion.com/job/ViaVersion/) or update your server software!` 

I connected to docker container to verify java version and it is 
`root@4299489d9af8:/# java --version`
`openjdk 19.0.1 2022-10-18`
`OpenJDK Runtime Environment (build 19.0.1+10-Ubuntu-1)`
`OpenJDK Server VM (build 19.0.1+10-Ubuntu-1, mixed mode, sharing)`
`

Please note that I had windows update running today and it restarted computer before trying to play so not sure if it is a coincidence but thought to mention.

Thank you,

Oleg

**Comment by TheRemote** [comment] 2023-03-15 19:58
Yes, 1.19.4 was released but Paper Minecraft 1.19.4 was not released yet.  This will happen every Minecraft update.

This update will be available when the Paper team releases it at page: https://papermc.io/downloads

The only way around this is to connect with an older Bedrock client (not easy to do since the Microsoft Store automatically updates it).

It typically only takes a day or two for the team to finish up the patch and then the newer Bedrock clients will be able to connect!

To be clear the problem is your Bedrock clients are updating themselves to what is essentially the Bedrock version of Java 1.19.4.  It has newer features in it that aren't ready for the server yet.  The Paper Minecraft team needs time to incorporate the new patch.

You might be able to use the ViaVersion plugin to bypass this possibly: https://www.spigotmc.org/resources/viaversion.19254/

Hopefully that helps!

**Comment by oscarmlage** [comment] 2023-03-15 19:59
Same error here, tried to play from iPad and it seems that there is an error trying to play with 1.19.70 version:

"Server does not support Java Edition 1.19.4, required for Geyser to connect. Server has to be updated or install ViaVersion plugin". And: "Disconnect message: Outdated server! I'm still on 1.19.3".

I've already restarted the container a couple of times because it says that it should update to the latest version by itself but didn't work. Also tried to force the `VERSION: 1.19.4` in the docker-compose variables but coulnd't be able to connect either.

Please tell me if I can help.
Thanks in advance .

**Comment by oscarmlage** [comment] 2023-03-15 20:21
> Hopefully that helps!

Sure! thanks for the explanation

**Comment by TheRemote** [comment] 2023-03-15 21:07
Actually I have something else for you guys to try.

Can you try closing the container and then doing a:

`docker pull 05jchambers/legendary-minecraft-geyser-floodgate:latest`

And try running again?

**Comment by oscarmlage** [comment] 2023-03-15 21:45
It works like a charm now with ViaVersion, thank you so much @TheRemote

**Comment by TheRemote** [comment] 2023-03-15 21:47
Fantastic!  I should have done it ages ago.  I'm so glad it worked out as well as it did.  It was a little tricky setting up the automatic updates but when I did I realized the Geyser and Floodgate ones were broken in the old version as well and needed a tweak.

This should smooth things over until 1.19.4 drops (and for all future updates) and reduce this pain point for everyone.

Thanks a ton for reporting back, enjoy and take care!

**Closed as completed by TheRemote** 2023-03-15 21:47 UTC

**Comment by vecnar** [comment] 2023-03-15 22:34
> To be clear the problem is your Bedrock clients are updating themselves to what is essentially the Bedrock version of Java 1.19.4. It has newer features in it that aren't ready for the server yet. The Paper Minecraft team needs time to incorporate the new patch.
> 
> You might be able to use the ViaVersion plugin to bypass this possibly: https://www.spigotmc.org/resources/viaversion.19254/
> 
> Hopefully that helps!

Thank you for explanation and issuing a quick fix!
